### ISSUE TITLE
msvc build not working

### ISSUE THREAD

**Issue by CarwynNelson** [tsoding/ded#16]
Tested on 0b7b6fdf7bceed017a907660e6a4794fe74a29db under windows 10, visual studio 2019.

If I run
```
setup_dependencies.bat
build_msvc.bat
```

And then If I run `ded.exe` from the command prompt I get the following error:
> The code execution cannot proceed because SDL2.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/3310215/124620029-061a7500-de71-11eb-9a6c-059c3085043a.png)

**Comment by Velho** [comment]
The shared libraries should be placed under the same directory as the executable. Should fix the issue.

**Comment by CarwynNelson** [comment]
> The shared libraries should be placed under the same directory as the executable. Should fix the issue.

So running `cp dependencies\SDL2\lib\x64\SDL2.dll SDL2.dll` seems to make it open and work correctly, but shouldn't the build script be doing this for you?

**Comment by Velho** [comment]
I suppose it is the case. Open a pull request, perhaps.
