### ISSUE TITLE
Better Name

### ISSUE THREAD

**Issue by rexim** [tsoding/ded#3]
We still didn't come up with the proper name. Leave your suggestions in the comments. The name should be short ('cause we don't wanna type too much in the terminal to start the editor) and memorable.

**Comment by xbelanch** [comment]
Maybe **Gramo** because it will be lighter and powerful than [Kilo](https://github.com/antirez/kilo)?

**Comment by moll-y** [comment]
I like the current one: **te**. It reminds me of **tea**.

**Comment by vipulmathur** [comment]
It could be called `tsode` or `tsoed`

**Comment by milochadam** [comment]
`te` - `tsode editor`

**Comment by kolumb** [comment]
Kod Editor
Kot Editor
© Coopert1n0 from Twitch chat

**Comment by rexim** [comment]
After the last PR #8 there was a suggestion to call the editor `dred`:
> yoda_droid: Lets rename this dred for DRamatic EDitor

**Comment by tarsiec** [comment]
I like the name JANE (Just ANother Editor), it sounds good and is self describing enough

**Comment by drocha87** [comment]
To me, as it's a Graphical Text Editor it should have `g` in the name. So I think `gtee` should be cool. `gtee` stands for `Graphical TExt Editor`

**Comment by BillKek** [comment]
tte (abbr. Tsoding text editor)
voidf (Because the background is dark like void)

**Comment by xbelanch** [comment]
*none*: non editor

**Comment by y1z** [comment]
txte pronounced (te-x-te)

**Comment by leanderbes** [comment]
tscode

**Comment by Donaim** [comment]
4tsoder (the [https://www.4coder.net/](4coder) evil twin)

**Comment by Brad-Hesson** [comment]
Maybe “txtea” pronounced texty.  Because of text and tea. Very paug in my opinion.

**Comment by rexim** [comment]
Thanks everyone for suggesting the name! I decided to call it `ded` for `Dramatic EDitor` as discussed on the stream.
