### ISSUE TITLE
Can't go to the previous folder, in the file browser

### ISSUE THREAD

**Issue by AverageAssemblyProgrammer** [tsoding/ded#59]
`.`
`..`
`<files>`

when you try to visit the `../` directory, using the file browser, it fails, on the assertion:-
`ded: src/common.c:102: read_entire_file: Assertion 'sb->items != NULL && "Buy more RAM lol"' failed.`

The problem is that my machine has 8 gigs of ram, which should be enough for a minimal editor like this, but I could be wrong.
Does anyone know, if the issue regarding my machine, or ded?

Memory: 3778MiB / 7833MiB
OS: Ubuntu 20.04.5 LTS x86_64
Kernel: 5.15.0-58-generic
CPU: Intel i5-9400 (6) @ 4.100GHz

Thanks.

**Comment by eloj** [comment]
There's no folder support currently:

https://github.com/tsoding/ded/blob/6bb06d32ebffb4dadf4a8ff4002bc4a5f58ea9e4/src/main.c#L201

You should get the error `Could not open file ..: Is a directory`, but the code isn't really robust enough to handle this well, as it relies on an error from `fopen()` when trying to open a directory.
