### ISSUE TITLE
build.sh using CRLF line terminators

### ISSUE THREAD

**Issue by jayhawker6** [tsoding/ded#70]
Shows it here:
[![asciicast](https://asciinema.org/a/p5khVwkQkdIzT6jsCC7SPb5UI.svg)](https://asciinema.org/a/p5khVwkQkdIzT6jsCC7SPb5UI)

The build.sh file didn't even show as executable beforehand because It wasn't the right file type, so I had to chmod +x build.sh. After fixing, out.sh worked without any changes. These issues are likely due to making the file with something that saved it to a DOS like format.

**Comment by BillKek** [comment]
![bui](https://user-images.githubusercontent.com/51540758/219178865-e4998871-b4c1-4cbb-87a1-dd04f6bb7fe2.png)

0x0D is not found.

**Comment by fabjan** [comment]
@jayhawker6 look at your `core.autocrlf` config in git, perhaps you had to use it for some other reason earlier and set it globally? https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by jayhawker6** [comment]
Think I fixed it. It seems to be a very bizarre WSL2 problem.
