### ISSUE TITLE
file_size() gives crazy big values back

### ISSUE THREAD

**Issue by PeriodGamingYT** [tsoding/ded#86]
./ded .
Loading .
bruh result 9223372036854775807 saved 0
bruh size 9223372036854775807
bruh cap 9223372036854775807 items 1 9223372036854775807
ded: src/common.c:109: read_entire_file: Assertion `sb->items != NULL && "Buy more RAM lol"' failed.
Aborted (core dumped)

after some diagnosing, fseek(fp, 0, SEEK_END) is giving back some crazy weird values.

**Comment by BillKek** [comment]
9223372036854775807  is 7FFFFFFFFFFFFFFF. Probably it is magic number of error code.

**Comment by PeriodGamingYT** [comment]
7FFFFFFFFFFFFFFF is not a magic number. Rather `(int) 0x7FFFFFFFFFFFFFFF` returns `-1`. So, `if(result < 0)` needs to be `if((int) result < 0)`.

**Comment by PeriodGamingYT** [comment]
Though, this fix gives a different error, which is probably me not giving a proper directory. The error now is `ERROR: Could not read file ./: Operation not permitted`. It thinks its trying to read a file. Maybe there's an option for that, or none at all. Not too sure.

**Comment by PeriodGamingYT** [comment]
So, you have to press F3 without specifying a directory. That's what takes you to the file browser. I think with the file error, we should also say something like `HELP: If you're trying to open a directory, use F3 inside the program.`.

**Comment by BillKek** [comment]
> Rather `(int) 0x7FFFFFFFFFFFFFFF` returns `-1`. So, `if(result < 0)` needs to be `if((int) result < 0)`.

No,no,no! Imagine that real file size is 5 GB. And (int32)filesize will be able to give < 0 !

**Comment by eloj** [comment]
The correct way to detect the error is to check `errno`.

**Comment by PeriodGamingYT** [comment]
Using fstat is probaly a better idea imo. Same thing intereting errno and not the return value of fseek.
