### ISSUE TITLE
ERROR: Could not initialize GLEW!

### ISSUE THREAD

**Issue by SatoTsukasaCode** [tsoding/ded#89]
Hey,
I am trying to install ded on Debian.
I have all of the dependencies installed but when i try to run `./ded src/main.c` i get:
```
Loading src/main.c
GL version 3.3
ERROR: Could not initialize GLEW!
```

**Comment by SatoTsukasaCode** [comment]
Looks to give me 0 or null

```
Loading src/main.c
GL version 3.3
ERROR: Could not initialize GLEW: 0
```

**Comment by rexim** [comment]
Wait! I was calling a wrong function! ea30e9d6ee1c0d52aa11f9386920b884987a6b55 Sorry! :D Could you please try again?

**Comment by SatoCodingStuff** [comment]
oh no
```
Loading src/main.c
GL version 3.3
ERROR: Could not initialize GLEW: Unknown error
```

**Comment by rexim** [comment]
Ok, I ran out of ideas for real this time :skull:

**Comment by SatoCodingStuff** [comment]
![image](https://github.com/tsoding/ded/assets/78177853/7ffce6a6-27df-47c4-a67a-172f1a1a6919)

**Comment by rexim** [comment]
:people_hugging:

**Comment by lambdasapple** [comment]
Are you by any chance running on Wayland?

**Comment by SatoCodingStuff** [comment]
i3 on xorg, i might try in gnome

**Comment by SatoCodingStuff** [comment]
looks to be getting the same error in gnome

**Comment by lambdasapple** [comment]
0 Should actually mean GLEW_OK... Can you remove the error check and try again?

**Comment by SatoCodingStuff** [comment]
```
GL version 3.3
WARNING: GLEW_ARB_debug_output is not availableSegmentation fault
```

**Comment by lambdasapple** [comment]
I've also ran out of ideas...

**Comment by SatoCodingStuff** [comment]
i switched back to arch and ded works so i'm going to close

**Comment by rexim** [comment]
Yoooo! Congrats! :tada:
